apiVersion: v1
kind: Service
metadata:
  name: gitea-lb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3000
    name: http
  selector:
    io.kompose.service: gitea
status:
  loadBalancer: {}
