apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: gitea
    spec:
      containers:
      - image: harbor.ucm.hlg.sld.cu/ucmho/gitea:1.0
        imagePullPolicy: ""
        name: gitea
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: gitea-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: gitea-volume
        nfs:
          server: 172.16.254.222
          # directory location on host
          path: /home/docker/gitea
          # this field is optional
